package com.rescuemate.ui.theme

import androidx.compose.ui.graphics.Color

// Cosmic Dark Theme Colors
val CosmicBackground = Color(0xFF0a0510)
val CosmicCard = Color(0xFF1a0f23)
val CosmicCardHover = Color(0xFF2d1420)
val CosmicBorder = Color(0xFF5A1E3C)
val CosmicPrimary = Color(0xFFE91E63)
val CosmicPrimaryDark = Color(0xFFC2185B)
val CosmicPrimaryLight = Color(0xFFFF1744)
val CosmicTextPrimary = Color(0xFFe8dff5)
val CosmicTextSecondary = Color(0xFFa89bb5)

// Material 3 Light Theme
val md_theme_light_primary = Color(0xFFE91E63)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD9E3)
val md_theme_light_onPrimaryContainer = Color(0xFF3F0014)
val md_theme_light_secondary = Color(0xFF5A1E3C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFF0a0510)
val md_theme_light_onBackground = Color(0xFFe8dff5)
val md_theme_light_surface = Color(0xFF1a0f23)
val md_theme_light_onSurface = Color(0xFFe8dff5)
val md_theme_light_surfaceVariant = Color(0xFF2d1420)
val md_theme_light_onSurfaceVariant = Color(0xFFa89bb5)
val md_theme_light_outline = Color(0xFF5A1E3C)
val md_theme_light_inverseOnSurface = Color(0xFFe8dff5)
val md_theme_light_inverseSurface = Color(0xFFe8dff5)
val md_theme_light_inversePrimary = Color(0xFFE91E63)
val md_theme_light_surfaceTint = Color(0xFFE91E63)
val md_theme_light_outlineVariant = Color(0xFF5A1E3C)
val md_theme_light_scrim = Color(0xFF000000)

// Material 3 Dark Theme (same as light for cosmic theme)
val md_theme_dark_primary = Color(0xFFE91E63)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFF5A1E3C)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD9E3)
val md_theme_dark_secondary = Color(0xFF5A1E3C)
val md_theme_dark_onSecondary = Color(0xFFFFFFFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0a0510)
val md_theme_dark_onBackground = Color(0xFFe8dff5)
val md_theme_dark_surface = Color(0xFF1a0f23)
val md_theme_dark_onSurface = Color(0xFFe8dff5)
val md_theme_dark_surfaceVariant = Color(0xFF2d1420)
val md_theme_dark_onSurfaceVariant = Color(0xFFa89bb5)
val md_theme_dark_outline = Color(0xFF5A1E3C)
val md_theme_dark_inverseOnSurface = Color(0xFFe8dff5)
val md_theme_dark_inverseSurface = Color(0xFFe8dff5)
val md_theme_dark_inversePrimary = Color(0xFFE91E63)
val md_theme_dark_surfaceTint = Color(0xFFE91E63)
val md_theme_dark_outlineVariant = Color(0xFF5A1E3C)
val md_theme_dark_scrim = Color(0xFF000000)

